# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20161122_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_localization',
            field=models.ManyToManyField(blank=True, through='houses.AgencyLocalization', to='houses.Barrio'),
        ),
    ]
