# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20161122_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_source_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
