# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_auto_20161123_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='ea_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='fc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='id_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provincia',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
