# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20161126_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='chalet_url',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
