# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_auto_20161126_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritorialEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.TerritorialEntity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Country')),
            ],
        ),
    ]
