# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_territorialentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='territorialentity',
            old_name='depth',
            new_name='depth_number',
        ),
        migrations.AddField(
            model_name='territorialentity',
            name='depth_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
