# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0020_territorialentity_near_brothers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorialentity',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.TerritorialEntity'),
        ),
        migrations.AlterField(
            model_name='territorialentity',
            name='near_brothers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='near_brother', to='houses.TerritorialEntity'),
        ),
    ]
