# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_auto_20161128_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='territorialentity',
            old_name='children',
            new_name='father',
        ),
    ]
