# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0029_auto_20161129_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsourceterritory',
            name='url_source_territory_name_list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
