# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0030_urlsourceterritory_url_source_territory_name_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialentity',
            name='depth_last',
            field=models.BooleanField(default=False),
        ),
    ]
