# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0031_territorialentity_depth_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsourceterritory',
            name='url_source_municipality_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
