# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0033_auto_20161202_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencysource',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencysource',
            name='source',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agency_source',
        ),
        migrations.DeleteModel(
            name='AgencySource',
        ),
    ]
