# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0034_auto_20161202_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyLocationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_source_name', models.CharField(max_length=200)),
                ('agency_source_url', models.CharField(max_length=200)),
                ('agency_localization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.AgencyLocalization')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Source')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='agency_location_source',
            field=models.ManyToManyField(blank=True, through='houses.AgencyLocationSource', to='houses.AgencyLocalization'),
        ),
    ]
