# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0036_auto_20161202_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=200),
        ),
    ]
