# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('idealista', 'idealista'), ('fotocasa', 'fotocasa'), ('enalquiler', 'enalquiler')], max_length=30)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=30)),
                ('transaction', models.CharField(choices=[('rent', 'rent'), ('buy', 'buy')], max_length=4, null=True)),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField(null=True)),
                ('house_type', models.CharField(choices=[('flat', 'piso'), ('house', 'chalet'), ('rustic', 'rustico'), ('duplex', 'duplex'), ('attic', 'atico')], max_length=6)),
                ('m2_total', models.IntegerField()),
                ('m2_to_use', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('desc', models.TextField()),
                ('flat_num', models.IntegerField()),
                ('outside', models.BooleanField()),
                ('energy_label', models.CharField(choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('No', 'No')], default='No', max_length=4)),
                ('orientation', models.CharField(choices=[('N', 'N'), ('NE', 'NE'), ('E', 'E'), ('S', 'S'), ('SW', 'SW'), ('W', 'W'), ('NW', 'NW')], max_length=2)),
                ('equipment', models.CharField(choices=[('A/C', 'A/C'), ('parking', 'parking')], max_length=2)),
                ('conditions', models.CharField(choices=[('good', 'good'), ('bad', 'bad')], max_length=2)),
                ('flat_num_total', models.IntegerField()),
                ('elevator', models.BooleanField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_online', models.BooleanField()),
                ('online_date', models.DateField(blank=True, null=True)),
                ('offline_date', models.DateField(blank=True, null=True)),
                ('address_comunidad', models.CharField(max_length=50, null=True)),
                ('address_province', models.CharField(max_length=50, null=True)),
                ('address_zona', models.CharField(max_length=50, null=True)),
                ('address_municipio', models.CharField(max_length=50, null=True)),
                ('address_area', models.CharField(max_length=50, null=True)),
                ('address_postal_code', models.IntegerField(null=True)),
                ('address_street', models.CharField(max_length=200, null=True)),
                ('address_number', models.IntegerField(null=True)),
                ('is_owner_real_state', models.BooleanField()),
                ('owner_phone', models.CharField(max_length=13)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Agency')),
            ],
        ),
    ]
