# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20161123_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='equipment',
        ),
        migrations.AddField(
            model_name='house',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='houses.Equipment'),
        ),
    ]
