# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20161123_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='flat_num_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
