# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20161124_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
