# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_source_chalet_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='sepatator_url',
            new_name='separator_url',
        ),
    ]
