# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0017_auto_20161127_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='houses.Equipment'),
        ),
    ]
