# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0018_auto_20161128_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='house_type_url',
            field=models.ManyToManyField(blank=True, through='houses.SourceHouseType', to='houses.HouseType'),
        ),
        migrations.AlterField(
            model_name='source',
            name='object_type_url',
            field=models.ManyToManyField(blank=True, through='houses.SourceObjectType', to='houses.ObjectType'),
        ),
        migrations.AlterField(
            model_name='source',
            name='territorial_url',
            field=models.ManyToManyField(blank=True, through='houses.URLSourceTerritory', to='houses.TerritorialEntity'),
        ),
        migrations.AlterField(
            model_name='source',
            name='transaction_url',
            field=models.ManyToManyField(blank=True, through='houses.SourceTransaction', to='houses.Transaction'),
        ),
    ]
