# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_auto_20161128_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcehousetype',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='sourcehousetype',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourceobjecttype',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='sourceobjecttype',
            name='source',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='house_type_url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='object_type_url',
        ),
        migrations.AddField(
            model_name='territorialentity',
            name='depth_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depth_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depth_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HouseType',
        ),
        migrations.DeleteModel(
            name='ObjectType',
        ),
        migrations.DeleteModel(
            name='SourceHouseType',
        ),
        migrations.DeleteModel(
            name='SourceObjectType',
        ),
    ]
