# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0024_auto_20161128_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='children',
            new_name='father',
        ),
    ]
