# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0028_auto_20161129_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorialentity',
            name='near_brothers',
            field=models.ManyToManyField(blank=True, related_name='_territorialentity_near_brothers_+', to='houses.TerritorialEntity'),
        ),
    ]
