# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0037_auto_20161202_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
