# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0038_agency_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
