# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0039_auto_20161221_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='desc',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
