# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0040_agency_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='outside',
            field=models.NullBooleanField(),
        ),
    ]
