# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0041_auto_20161223_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_completed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='is_online',
            field=models.NullBooleanField(),
        ),
    ]
