# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0044_auto_20161225_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_source_id', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='house',
            old_name='source',
            new_name='source_house',
        ),
        migrations.RemoveField(
            model_name='house',
            name='house_source_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='price',
        ),
        migrations.RemoveField(
            model_name='house',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='house',
            name='title',
        ),
        migrations.RemoveField(
            model_name='house',
            name='url',
        ),
        migrations.AddField(
            model_name='sourcehouse',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
        migrations.AddField(
            model_name='sourcehouse',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Source'),
        ),
    ]
