# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0047_auto_20161226_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='agency',
            field=models.ManyToManyField(blank=True, help_text='If blank there is not an agency involved', to='houses.Agency'),
        ),
    ]
