# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0049_auto_20161226_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcehouse',
            name='house',
        ),
        migrations.RemoveField(
            model_name='sourcehouse',
            name='source',
        ),
        migrations.RemoveField(
            model_name='house',
            name='source_house',
        ),
        migrations.DeleteModel(
            name='SourceHouse',
        ),
    ]
