# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0050_auto_20161226_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_source_id', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('is_completed', models.NullBooleanField(default=False)),
                ('is_online', models.NullBooleanField()),
                ('online_date', models.DateField(blank=True, null=True)),
                ('offline_date', models.DateField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Source')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='source_house',
            field=models.ManyToManyField(blank=True, through='houses.SourceHouse', to='houses.Source'),
        ),
    ]
