# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0053_auto_20161228_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcehouse',
            name='page',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
