# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0054_sourcehouse_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcehouse',
            name='page',
            field=models.CharField(max_length=2000000, null=True),
        ),
    ]
