# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0057_auto_20161228_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner_phone',
        ),
        migrations.AddField(
            model_name='sourcehouse',
            name='agency',
            field=models.ManyToManyField(blank=True, help_text='If blank there is not an agency involved', to='houses.Agency'),
        ),
        migrations.AddField(
            model_name='sourcehouse',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='sourcehouse',
            name='owner_phone_2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
