# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0058_auto_20161229_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcehouse',
            old_name='owner_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='sourcehouse',
            old_name='owner_phone_2',
            new_name='phone_2',
        ),
        migrations.AlterField(
            model_name='sourcehouse',
            name='agency',
            field=models.ManyToManyField(blank=True, help_text='If blank there is not an agency involved', to='houses.AgencyLocalizationSource'),
        ),
    ]
