# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0059_auto_20161229_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcehouse',
            old_name='agency',
            new_name='agency_location_source',
        ),
    ]
