# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0061_auto_20161229_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcehouse',
            name='agency_location_source',
            field=models.ManyToManyField(blank=True, help_text='If blank there is not an agency involved', to='houses.AgencyLocalizationSource'),
        ),
    ]
