# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0062_auto_20161229_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcehouse',
            name='slug',
        ),
        migrations.AddField(
            model_name='house',
            name='m2_terrain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
