# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0063_auto_20161230_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_source_id', models.CharField(max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(null=True)),
                ('is_completed', models.NullBooleanField(default=False)),
                ('is_online', models.NullBooleanField()),
                ('online_date', models.DateField(blank=True, null=True)),
                ('offline_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=13, null=True)),
                ('agency_location_source', models.ManyToManyField(blank=True, help_text='If blank there is not an agency involved', to='houses.AgencyLocalizationSource')),
            ],
        ),
        migrations.RemoveField(
            model_name='sourcehouse',
            name='agency_location_source',
        ),
        migrations.RemoveField(
            model_name='sourcehouse',
            name='house',
        ),
        migrations.RemoveField(
            model_name='sourcehouse',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourcehouse',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house',
            name='energy_label',
        ),
        migrations.RemoveField(
            model_name='house',
            name='id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='source_house',
        ),
        migrations.RemoveField(
            model_name='house',
            name='territorial_entity',
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, choices=[('A+++', 'A+++'), ('A++', 'A++'), ('A+', 'A+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
            ],
            bases=('houses.property',),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
            ],
            bases=('houses.property',),
        ),
        migrations.CreateModel(
            name='Industrial',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
            ],
            bases=('houses.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
            ],
            bases=('houses.property',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
            ],
            bases=('houses.property',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
            ],
            bases=('houses.property',),
        ),
        migrations.DeleteModel(
            name='SourceHouse',
        ),
        migrations.AddField(
            model_name='sourceproperty',
            name='property_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Property'),
        ),
        migrations.AddField(
            model_name='sourceproperty',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Source'),
        ),
        migrations.AddField(
            model_name='sourceproperty',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_transacion_house', to='houses.Transaction'),
        ),
        migrations.AddField(
            model_name='property',
            name='source_property',
            field=models.ManyToManyField(blank=True, through='houses.SourceProperty', to='houses.Source'),
        ),
        migrations.AddField(
            model_name='property',
            name='territorial_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='house',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, default='1', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property'),
            preserve_default=False,
        ),
    ]
