# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0066_auto_20161231_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercial',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='industrial',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='land',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='office',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='room',
            name='property_ptr',
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='Garage',
        ),
        migrations.DeleteModel(
            name='Industrial',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
