# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0067_auto_20170102_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_value', models.IntegerField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction',
            field=models.CharField(blank=True, choices=[('rent', 'rent'), ('sale', 'sale')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.ManyToManyField(blank=True, to='houses.Price'),
        ),
    ]
