# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0069_auto_20170103_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='agency',
            new_name='real_estate',
        ),
    ]
