# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0072_auto_20170103_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_raw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
