# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0074_auto_20170103_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bathrooms',
            new_name='wc',
        ),
    ]
