# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0075_auto_20170103_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.DateField(blank=True, null=True)),
                ('offline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price_value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='offline_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='online_date',
        ),
        migrations.AddField(
            model_name='date',
            name='property_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.Property'),
        ),
    ]
