# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0077_realestate_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='source_url',
            new_name='web',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='source_id',
        ),
        migrations.AddField(
            model_name='realestate',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
