# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 09:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0080_auto_20170106_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5000, null=True), null=True, size=None),
        ),
    ]
