# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0081_auto_20170108_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='condition',
            new_name='preservation',
        ),
        migrations.AddField(
            model_name='house',
            name='air_conditioning',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='builtin_wardrobes',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='clotheslineSpace',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='elevator',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='furnished',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='furnished_kitchen',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='garage',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='store_room',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='swimming_pool',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='house',
            name='terrace',
            field=models.NullBooleanField(),
        ),
    ]
