# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0082_auto_20170108_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='air_conditioning',
            new_name='air_conditioner',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='clotheslineSpace',
            new_name='chimney',
        ),
        migrations.AddField(
            model_name='house',
            name='garden',
            field=models.NullBooleanField(),
        ),
    ]
