# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0087_auto_20170109_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='people_now_living_female',
            new_name='looking_for_female',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='people_now_living_male',
            new_name='looking_for_male',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='looking_for_gender',
            new_name='people_now_living_gender',
        ),
    ]
