# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0088_auto_20170109_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
                ('m2_total', models.IntegerField(blank=True, null=True)),
                ('m2_to_use', models.IntegerField(blank=True, null=True)),
                ('m2_terrain', models.IntegerField(blank=True, null=True)),
                ('num_of_flats', models.IntegerField(blank=True, null=True)),
                ('distribution', models.CharField(blank=True, max_length=200, null=True)),
                ('kitchen', models.NullBooleanField()),
                ('wc', models.IntegerField(blank=True, null=True)),
                ('wc_inside_office', models.NullBooleanField()),
                ('orientation', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('norte', 'norte'), ('noreste', 'noreste'), ('este', 'este'), ('sureste', 'sureste'), ('sur', 'sur'), ('suroeste', 'suroeste'), ('oeste', 'oeste'), ('noroeste', 'noroeste')], max_length=30, null=True)),
                ('garage', models.NullBooleanField()),
                ('flat_num', models.CharField(blank=True, max_length=200, null=True)),
                ('building_total_flats_num', models.CharField(blank=True, max_length=200, null=True)),
                ('outside', models.CharField(blank=True, max_length=20, null=True)),
                ('elevators', models.IntegerField(blank=True, null=True)),
                ('office_type', models.CharField(blank=True, max_length=20, null=True)),
                ('janitor', models.NullBooleanField()),
                ('access_control', models.NullBooleanField()),
                ('security_system', models.NullBooleanField()),
                ('security_door', models.NullBooleanField()),
                ('fire_extinguishers', models.NullBooleanField()),
                ('fire_detectors', models.NullBooleanField()),
                ('Sprinklers', models.NullBooleanField()),
                ('fire_door', models.NullBooleanField()),
                ('emergency_exit', models.NullBooleanField()),
                ('emergency_exit_lights', models.NullBooleanField()),
                ('hot_water', models.NullBooleanField()),
                ('heating', models.NullBooleanField()),
                ('air_conditioning_cold', models.NullBooleanField()),
                ('air_conditioning_hot', models.NullBooleanField()),
                ('double_glazed_windows', models.NullBooleanField()),
                ('false_ceiling', models.NullBooleanField()),
            ],
            bases=('houses.property',),
        ),
        migrations.RenameField(
            model_name='house',
            old_name='air_conditioner',
            new_name='air_conditioning',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='air_conditioner',
            new_name='air_conditioning',
        ),
    ]
