# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0089_auto_20170109_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='wc_inside_office',
            new_name='false_floor',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='building_total_flats_num',
            new_name='wc_location',
        ),
        migrations.AddField(
            model_name='office',
            name='preservation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
