# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0090_auto_20170109_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='Sprinklers',
            new_name='sprinklers',
        ),
    ]
