# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0093_auto_20170109_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='phone_1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
