# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0094_auto_20170109_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
                ('m2_total', models.IntegerField(blank=True, null=True)),
                ('m2_min_rent', models.IntegerField(blank=True, null=True)),
                ('m2_min_sale', models.IntegerField(blank=True, null=True)),
                ('m2_to_build', models.IntegerField(blank=True, null=True)),
                ('access', models.CharField(blank=True, max_length=200, null=True)),
                ('nearest_town', models.CharField(blank=True, max_length=200, null=True)),
                ('ground', models.CharField(blank=True, max_length=200, null=True)),
                ('zoned', models.CharField(blank=True, max_length=200, null=True)),
                ('building_floors', models.IntegerField(blank=True, null=True)),
                ('sewerage', models.NullBooleanField()),
                ('street_lighting', models.NullBooleanField()),
                ('water', models.NullBooleanField()),
                ('electricity', models.NullBooleanField()),
                ('sidewalks', models.NullBooleanField()),
                ('natural_gas', models.NullBooleanField()),
            ],
            bases=('houses.property',),
        ),
        migrations.RenameField(
            model_name='house',
            old_name='flat_num',
            new_name='floor_num',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='flat_num',
            new_name='floor_num',
        ),
        migrations.RenameField(
            model_name='office',
            old_name='num_of_flats',
            new_name='num_of_floors',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='flat_num',
            new_name='floor_num',
        ),
    ]
