# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0096_auto_20170109_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='online',
            field=models.NullBooleanField(default=True),
        ),
    ]
