# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0098_auto_20170117_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
