# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0102_auto_20170123_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
