# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0105_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='coordinates',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
