# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0106_property_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='coordinates',
        ),
    ]
