# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0109_property_address_exact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
