# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0111_auto_20170404_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='wc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
