# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0112_auto_20170404_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='commercial_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
