# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0113_commercial_commercial_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
                ('m2_total', models.IntegerField(blank=True, null=True)),
                ('m2_min_rent', models.IntegerField(blank=True, null=True)),
                ('building_type', models.CharField(blank=True, max_length=200, null=True)),
                ('elevators', models.IntegerField(blank=True, null=True)),
                ('floor_num', models.CharField(blank=True, max_length=200, null=True)),
                ('garages_num', models.CharField(blank=True, max_length=200, null=True)),
                ('security', models.NullBooleanField()),
                ('preservation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('houses.property',),
        ),
        migrations.CreateModel(
            name='StoreRoom',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='houses.Property')),
                ('m2_total', models.IntegerField(blank=True, null=True)),
                ('m_height', models.IntegerField(blank=True, null=True)),
                ('access_24h', models.NullBooleanField()),
                ('limited_parking', models.NullBooleanField()),
            ],
            bases=('houses.property',),
        ),
    ]
