# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0114_building_storeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='houses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='tenant',
            field=models.NullBooleanField(),
        ),
    ]
