# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0115_auto_20180112_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='elevators',
            new_name='elevator_num',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='garages_num',
            new_name='garage_num',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='houses',
            new_name='house_num',
        ),
        migrations.AddField(
            model_name='building',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
