# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0116_auto_20180112_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'house'), ('room', 'room'), ('office', 'office'), ('garage', 'garage'), ('land', 'land'), ('commercial', 'commercial'), ('storeroom', 'storeroom'), ('building', 'building')], max_length=200, null=True),
        ),
    ]
