# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0117_auto_20180112_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='tenant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
