# Generated by Django 2.0.1 on 2018-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0118_auto_20180112_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
