# Generated by Django 2.0.1 on 2018-01-19 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0119_auto_20180118_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_path',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
        ),
    ]
