# Generated by Django 2.0.1 on 2018-02-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0120_property_address_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TerritorialEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code_idelista', models.CharField(blank=True, max_length=50, null=True)),
                ('name_idealista', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='father', null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.TerritorialEntity')),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='real_estate',
            field=models.ForeignKey(blank=True, help_text='If blank there is not a real estate involved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='houses.RealEstate'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d00',
            field=models.ForeignKey(blank=True, help_text='world', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='world', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d01',
            field=models.ForeignKey(blank=True, help_text='continent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continent', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d02',
            field=models.ForeignKey(blank=True, help_text='country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d03',
            field=models.ForeignKey(blank=True, help_text='province', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d04',
            field=models.ForeignKey(blank=True, help_text='zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d05',
            field=models.ForeignKey(blank=True, help_text='area', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d06',
            field=models.ForeignKey(blank=True, help_text='municipality', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipality', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d07',
            field=models.ForeignKey(blank=True, help_text='district', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d08',
            field=models.ForeignKey(blank=True, help_text='neighbourhood', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighbourhood', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d09',
            field=models.ForeignKey(blank=True, help_text='XX00', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='XX00', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='geocode',
            name='d10',
            field=models.ForeignKey(blank=True, help_text='XX01', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='XX01', to='houses.TerritorialEntity'),
        ),
        migrations.AddField(
            model_name='property',
            name='address_geocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='houses.GeoCode'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='geocode',
            field=models.ManyToManyField(to='houses.GeoCode'),
        ),
    ]
