# Generated by Django 2.0.1 on 2018-02-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0121_auto_20180209_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='territorialentity',
            old_name='code_idelista',
            new_name='code_idealista',
        ),
    ]
