# Generated by Django 2.0.1 on 2018-02-09 19:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0123_auto_20180209_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='geocode_raw',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
        ),
    ]
