# Generated by Django 2.0.1 on 2018-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0125_auto_20180213_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorialentity',
            name='code_idealista_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
